version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: |
          javac Athena.java\
          jar cfe Athena.jar Athena Athena.class\
          git add Athena.jar\
          run: git push
