version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      version: 0.0.2
      build: 1
    steps:
      - checkout
      - run: |
          if [ ! -d $version ]; then
            mkdir $version
            echo "p"
          fi

          javac Main.java
          jar cfe $version/Athena-$build.jar Main Main.class

          git config --global user.email "zeraoramc@outlook.com"
          git config --global user.name "ZeraMC"

          git add $version/Athena-$build.jar
          git commit -m "[ci skip]"
          git push

      - run: java -jar -Xmx10G -Xms10G Athena.jar
      - store_artifacts:
          path: $version/Athena-$build.jar
          destination: Artifacts
