version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: |
          javac Athena.java
          jar cfe Athena.jar Athena Athena.class

          git config --global user.email "zeraoramc@outlook.com"
          git config --global user.name "ZeraMC"

          git add Athena.jar
          git commit -m "[ci skip]"
          git push
