version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      version: 0.0.2
      build: 1
    steps:
      - checkout
      - run:
          name: Checking if version directory exists
          command: |
            if [ ! -d $version ]; then
              mkdir $version
            fi

          name: Compiling java files to class files
          command: javac Main.java

          name: Adding class files to jar archive
          command: jar cfe $version/Athena-$build.jar Main Main.class

          name: Setting github account to commit with
          command: |
            git config --global user.email "zeraoramc@outlook.com"
            git config --global user.name "ZeraMC"

          name: Commiting jar archive to github
          command: |
            git add $version/Athena-$build.jar
            git commit -m "[ci skip]"
            git push

          name: Running jar archive
          command: java -jar -Xmx10G -Xms10G $version/Athena-$build.jar
      - store_artifacts:
          path: $version/Athena-$build.jar
          destination: Artifacts
