version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: javac Athena.java
      - run: jar cfe Athena.jar Athena Athena.class
      - run: git add Athena.jar
      - run: git push
