version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: |
          find -name "*.java" > sources.txt
          javac @sources.txt
          find -name "*.class" > sources.txt
          jar c @sources.txt

          git config --global user.email "zeraoramc@outlook.com"
          git config --global user.name "ZeraMC"

          find -name "*.jar" > sources.txt
          git add @sources.txt
          git commit -m "[ci skip]"
          git push
