version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk-11.0.3-jdk
    steps:
      - checkout
      - run: read name
      - run: javac $name.java
      - run: jar cfe $name.jar $name $name.class
